# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
       # run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Get a list of files over 256x
        run: |
          sudo apt install libimage-exiftool-perl;
          exiftool -q -r -ext png -if '$ImageHeight > 256 && $ImageWidth > 256' -p '$Directory/$FileName' assets/minecraft/textures/ >> 256_errors.txt;
          echo Test Command. I have no clue if this will work.;
          sed -i '/gui/d' 256_errors.txt
          sed -i '/clothing/d' 256_errors.txt
          pastebinit -i 256_errors.txt;
          
      - name: Send errors to Discord Webhook
        env: 
          DISCORD_URL:  ${{ secrets.DISCORDWEBHOOK }}
        run: |
          echo "==Images over 256x==" >> errors.txt
          cat 256_errors.txt >> errors.txt
          link=($(pastebinit -i errors.txt))
          wc 256_errors.txt > err_1
          read lines words characters filename < err_1 
          errors=$lines+0
          curl -X POST -H "Content-Type: application/json" -d '{"username": "Resource Pack Test", "content": "There are '"$errors"' errors in the pack. Link: "'$link"'"}' $DISCORD_URL
          
          
